### ISSUE TITLE
More easily iterate over entities with multiple components

### ISSUE THREAD

**Issue by MindSwipe** [njelly/TofuECS#4]
Currently, when wanting to iterate over entities with multiple components, we need to query the buffer for each individual component type. like

```csharp
var i = s.Buffer<Coordinate>().GetIterator();
var speedBuffer = s.Buffer<Speed>();

while (i.Next())
{
    iterator.Get(out var coord);
    speedBuffer.Get(i.Entity, out var speed);

    Console.WriteLine($"Entity {i.Entity} is at {coord} and is going {speed}");
}
```

I'd like something more ergonomic/ more performant, either

```csharp
s.Buffer<(Coordinate, Speed)>();
```

Or if that isn't possible

```csharp
s.Buffer<Coordinate>().And<Speed>();
```

**Comment by njelly** [comment]
Sounds like this is a popular feature based on feedback I've gotten, so it should definitely be added.

I really like the look of the second of one ([and the currying style in general](https://en.wikipedia.org/wiki/Currying)) so I think it should look similar, although maybe get it from the simulation directly like this?:

```
s.Query<Coordinate>().And<Speed>().And<SomeOtherComponent>().GetIterator();
```

Which returns a multi-component iterator with just the `Coordinate` and `Speed` and `SomeOtherComponent` components that are associated with the same entity.  The problem is how to go about doing that... I'd like to not have to 'register' iterators like you need to do with components, and I'd like it to not slow down adding/removing components from entities too much.

I'll think about it. :)

**Comment by njelly** [comment]
This is done. [I have added `ComponentQuery`.](https://github.com/njelly/TofuECS/blob/main/TofuECS/ComponentQuery.cs)
